### ISSUE TITLE
is the code working on windows?

### ISSUE THREAD

**Issue by yahyaelezaby** [openremote/or-objectdetection#40]
we are trying to run the code on windows following the same way in your video, but we are facing this error. and of course we made sure of all the requirements that you motioned (CUDA, Python3, OpenCV, pyQT, pyTorch, torchVision) still we are getting the same problem 
![WhatsApp Image 2020-11-24 at 17 00 38](https://user-images.githubusercontent.com/74975734/100115405-26199d00-2e7b-11eb-89c3-6ceaf3720e51.jpeg)

is the code working on windows?

**Comment by Code-King** [comment]
The First part of the Code is working   , having issues with the following 
from analyse import *
from models import *
from utils import *
from sort import *

**Comment by haviduck** [comment]
is python3 in your path env?

**Comment by LuukEbenau** [comment]
The new release of the application is running completely inside docker.
We support linux out of the box, given you have the right cuda version on the host pc.
For windows its a bit more tricky, since you need nvidia-docker to run the application.
WSL2 has experimental support for nvidia docker, if that works the application should work fine on windows.
